### PR TITLE
Authorization Enablement & Example

### PR DESCRIPTION
**Pull request by nbauernfeind**
The old pull-request was fubar because github thought my fork was a source and not an actual fork; I was unable to update the request.

I've rebased the changes onto master, updated commit timestamps (or else github creates a pull-request fubar), addressed your comments from October, and did a good ol' once over on my own.

Let me know whatever else I can do.

Thanks,
Nate

### CODE REVIEW

**Comment by joeslice** [comment]
Jenkins please whitelist.

**Comment by joeslice** [comment]
add to whitelist

**Comment by joeslice** [comment]
Jenkins please test.

**Comment by jsurls** [comment]
Closing due to age. Lets discuss before another PR with these changes are opened.

**Pull request closed without merging**
