### PR TITLE
Jersey-based HMAC authentication for the Jersey 2.x client Fixes #57

### LINKED ISSUE #57: Jersey-based HMAC authentication for the Jersey 2.x client
It would be great to have Jersey 2.x client with HMAC authentication. I can't use older version of authentication client, because recent versions of Dropwizard contain Jersey 2.x client which conflicts with Jersey 1.x client

### PR DESCRIPTION
**Pull request by amykytchyn**
Implementation of Jersey-based HMAC authentication for the Jersey 2.x client (see #57)

### CODE REVIEW

**Comment by DhruvitBV** [comment]
I noticed that for client2, the HmacClientFilter does not specify endpoints to add security credentials  to outgoing requests like client1 does. What is the reason for this difference in behavior?
Also, could you please update the readme to include support for jersey 2.x?

**Comment by amykytchyn** [comment]
@DhruvitBV Thank you for reviewing, could you please check updated version?

**Comment by DhruvitBV** [comment]
retest this please (testing jenkins build trigger)

**Comment by DhruvitBV** [comment]
retest this please (testing again)

**Pull request merged**
