### PR TITLE
Authorization Example

### PR DESCRIPTION
**Pull request by nbauernfeind**
I did a couple of other things for consistency sake, see commit comments for a good breakdown.

The primary thing to look at is the documentation on the main readme, and the new sample application.

Let me know whatever you think we can make better!

Fixes #20

### CODE REVIEW

**Comment by joeslice** [comment]
@nbauernfeind I'd like to get this contribution into the mainline.  If you can make your repo public I can take the next steps.  Thanks!

**Comment by joeslice** [comment]
Jenkins add to whitelist.

**Comment by nbauernfeind** [comment]
I'm rebasing at this moment and trying to tie everything together. FYI: `HmacClientFilterTest` has three failing tests on master.

**Comment by nbauernfeind** [comment]
Note that HmacAuthProvider is abstract because otherwise, due to erasure, Jersey is unable to determine what AnnotationType it is supposed to be looking for during injection. When you extend a class that has generic types with explicit types the data gets stored along with the class and is available at runtime. It's a clever trick that Jackson's TypeReference, Guice's TypeLiteral, and Guava's TypeToken all use.

**Comment by nbauernfeind** [comment]
Sometimes I hate how github treats timestamps on commit messages during pull-requests.

**Comment by joeslice** [comment]
Superceded by #44.

**Pull request closed without merging**
